#!/bin/sh

# One-char access
alias v='vim -p'
alias s='ssh'
alias g='git'

# command updated
alias ls='ls -p' # -p writes '/' after directories
alias vi='vim -p' # open vim in tabs
alias vim='vim -p'

# Document access
alias bashrc='nvim ~/.bash/.bashrc'
alias host='sudo vim /etc/hosts'
alias hosts='sudo vim /etc/hosts'

# Better cp
alias cp='cp -r'

# Navigation
alias ll='ls -lh'

# Need iterm and title function for this one
alias t='title'

# Redis
alias redis-server='redis-server /usr/local/etc/redis.conf'

# Vagrant
alias vd='vagrant destroy'
alias vh='vagrant halt'
alias vp='vagrant provision'
alias vpr='vagrant provision'
alias vr='vagrant reload'
alias vs='vagrant status'
alias vssh='vagrant ssh'
alias vup='vagrant up'
alias valias='alias|grep vagrant|grep -v grep'
alias valiases='alias|grep vagrant|grep -v grep'

# power
alias sd='sudo shutdown -h now' # Shutdown
alias po='sudo shutdown -h now' # Poweroff (same as shutdown)

# Searching
alias grep='grep --color=always'

# git
alias gitconf='vim ~/.gitconfig'
alias gitconfig='vim ~/.gitconfig'

# Web
alias serve='python -m SimpleHTTPServer 8080'

# Demo
alias keys='key-mon'

# docker
alias dc='docker-compose'
alias dm='docker-machine'
alias dclean='docker rm --force --volumes $(docker ps -a -q); docker rmi $(docker images | grep "<none>" | awk "{print $3}")'

# reload bashrc
alias sbash='source ~/.bash_profile'

# colors
RESTORE=$(echo -en '\033[0m')
RED=$(echo -en '\033[00;31m')
GREEN=$(echo -en '\033[00;32m')
YELLOW=$(echo -en '\033[00;33m')
BLUE=$(echo -en '\033[00;34m')
MAGENTA=$(echo -en '\033[00;35m')
PURPLE=$(echo -en '\033[00;35m')
CYAN=$(echo -en '\033[00;36m')
LIGHTGRAY=$(echo -en '\033[00;37m')
LRED=$(echo -en '\033[01;31m')
LGREEN=$(echo -en '\033[01;32m')
LYELLOW=$(echo -en '\033[01;33m')
LBLUE=$(echo -en '\033[01;34m')
LMAGENTA=$(echo -en '\033[01;35m')
LPURPLE=$(echo -en '\033[01;35m')
LCYAN=$(echo -en '\033[01;36m')
WHITE=$(echo -en '\033[01;37m')
