#!/usr/bin/env bash

######################
# Sourcing other files
######################
source ~/.profile

source $HOME/.dotfiles/bash/bzshrc


# git completion
# source $HOME/.dotfiles/git/git-completion.sh
# __git_complete g __git_main

# git prompt
# if [ -f $DIR/git-prompt/gitprompt.sh ]; then
#   source $DIR/git-prompt/gitprompt.sh
#   GIT_PROMPT_ONLY_IN_REPO=1
#   GIT_PROMPT_THEME=Solarized_Ubuntu
# fi

# Fuzzy finder
# [ -f ~/.fzf.bash ] && source ~/.fzf.bash

# autocompletion for sudo
complete -cf sudo

# Always color grep output, even when piping
export GREP_OPTIONS='--color=always'

## Cylcle through completions ###
# [[ $- = *i* ]] && bind TAB:menu-complete
# [[ $- = *i* ]] && bind CONTROL-k:menu-complete
# [[ $- = *i* ]] && bind CONTROL-j:menu-complete-backward

## Ignore case with completion ##
bind 'set completion-ignore-case on'
## Show list after the first tab ##
set show-all-if-ambiguous on

## Minor spell checking with cd ##
shopt -s cdspell

## Case insensitice Filename matching / completions ##
set completion-ignore-case on

## Bash will append (not overwrite) history on disk ##
shopt -s histappend
## Write previous line to disk ##
# PROMPT_COMMAND='history -a'


# start z shell
# zsh
